<?php if (Mage::getStoreConfigFlag('google/analytics/active')): ?>
<script type="text/javascript">		
    if (Mage.Cookies.get("BA") === null) {
        var testBandwidth = (Math.floor((Math.random() * 100)) % 33 == 0);         
    } 
    BOOMR.init({
        beacon_url: null,
	  BW: {
        base_url: "/skin/frontend/base/default/images/boomerang/",
        enabled: testBandwidth,
        site_domain: '<?php echo Mage::getStoreConfig("web/cookie/cookie_domain"); ?>'
      }
    });
    BOOMR.subscribe('before_beacon', function(o){
        bwLatResult = formatBwLatency(testBandwidth, o);
       	_gaq.push(['_setCustomVar', 4, 'Bandwidth', bwLatResult.bandwidth, 1]);
       	_gaq.push(['_setCustomVar', 5, 'Latency', bwLatResult.latency, 1]);        	

        _gaq.push(['_setSiteSpeedSampleRate', 100]);
        //Filtering out noise
        if (o.t_done && o.t_done <=60000) {
            _gaq.push(['_trackTiming', '<?php echo $this->getPageType(); ?>' ,'Pageview', o.t_done ]);         
        }
        _gaq.push(['_trackEvent', '<?php echo $this->getPageType(); ?>', 'Pageview']);
    });

</script>
<?php endif ?>